"""Database connection and schema for case persistence.

Dual backend, chosen by the connection target:

* a ``postgres://`` / ``postgresql://`` URL  -> Postgres via psycopg (production,
  e.g. Railway's Postgres plugin, which injects ``DATABASE_URL``).
* anything else                              -> a local SQLite file path (or
  ``:memory:`` for tests) via the standard library.

Both backends store identical columns and the same JSON payloads, so the rest of
the app and the "recompute from stored canonical inputs" model are unchanged.
psycopg is imported lazily, so SQLite-only environments (local dev, the default
test run) need no extra dependency.
"""

from __future__ import annotations

import sqlite3
from pathlib import Path
from typing import Any

# SQLite uses AUTOINCREMENT; Postgres uses an identity/serial column. Everything
# else (TEXT columns holding ISO timestamps and JSON) is identical.
_SQLITE_TABLE = """
CREATE TABLE IF NOT EXISTS cases (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    module       TEXT NOT NULL,          -- 'earnings' | 'lcp' | 'lhhs'
    title        TEXT NOT NULL,
    created_at   TEXT NOT NULL,          -- ISO-8601 UTC
    updated_at   TEXT NOT NULL,
    inputs_json  TEXT NOT NULL,          -- canonical input dict (decimals)
    summary_json TEXT NOT NULL           -- totals for listings
)
"""

_POSTGRES_TABLE = """
CREATE TABLE IF NOT EXISTS cases (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    module       TEXT NOT NULL,
    title        TEXT NOT NULL,
    created_at   TEXT NOT NULL,
    updated_at   TEXT NOT NULL,
    inputs_json  TEXT NOT NULL,
    summary_json TEXT NOT NULL
)
"""

_INDEX = "CREATE INDEX IF NOT EXISTS idx_cases_module ON cases(module)"


def is_postgres_url(target: str) -> bool:
    return target.startswith(("postgres://", "postgresql://"))


def connect(target: str) -> Any:
    """Open a connection to ``target`` (a Postgres URL or a SQLite path).

    For SQLite, creates the parent directory if needed so a mounted-volume path
    like ``/data/forensic_calc.sqlite`` works on first boot. Rows are name-
    addressable on both backends (``sqlite3.Row`` / psycopg ``dict_row``), so
    callers can index columns by name uniformly.
    """
    if is_postgres_url(target):
        import psycopg
        from psycopg.rows import dict_row

        # Railway historically exposes postgres://; psycopg wants postgresql://.
        dsn = target.replace("postgres://", "postgresql://", 1)
        return psycopg.connect(dsn, row_factory=dict_row)

    if target != ":memory:":
        Path(target).expanduser().resolve().parent.mkdir(parents=True, exist_ok=True)
    conn = sqlite3.connect(target)
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA foreign_keys = ON;")
    return conn


def init_db(conn: Any) -> None:
    """Create the cases table and index if they do not exist (idempotent)."""
    table = _SQLITE_TABLE if isinstance(conn, sqlite3.Connection) else _POSTGRES_TABLE
    cur = conn.cursor()
    try:
        cur.execute(table)
        cur.execute(_INDEX)
    finally:
        cur.close()
    conn.commit()
